-- MySQL Workbench Synchronization
-- Generated: 2016-01-19 20:34
-- Model: MMU Mini Project Model
-- Version: 1.0
-- Project: MMU Mini Project Model
-- Author: Emyliana

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `student` 
DROP FOREIGN KEY `fk_STUDENT_FACULTY1`;

ALTER TABLE `student` 
DROP COLUMN `fac_id`,
DROP INDEX `fk_STUDENT_FACULTY1_idx` ;

ALTER TABLE `specialization` 
ADD COLUMN `fac_id` INT(11) NOT NULL AFTER `spec_name`,
ADD INDEX `fk_specialization_faculty1_idx` (`fac_id` ASC);

ALTER TABLE `specialization` 
ADD CONSTRAINT `fk_specialization_faculty1`
  FOREIGN KEY (`fac_id`)
  REFERENCES `faculty` (`fac_id`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
